sudo: required
services:
  - docker

before_install:
  - docker build -t arunkumar2669/learningdocker -f Dockerfile.dev .

script:
  - docker run arunkumar2669/learningdocke npm run test -- --coverage
